<div class="container-fluid px-4">
    <h1 class="mt-4">Usuários</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="/usuario">Usuários</a></li>
        <li class="breadcrumb-item active">Cadastrar</li>
    </ol>

    <?php
    // dd($this->view->status);
    if (isset($this->view->status) && $this->view->status['status'] == "ERROR") {
    ?>
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <strong>MENSAGEM: </strong> <?= $this->view->status['msg'] ?>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    <?php
    }
    ?>

<?php
    // dd($this->view->status);
    if (isset($this->view->status) && $this->view->status['status'] == "SUCCESS") {
    ?>
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <strong>MENSAGEM: </strong> <?= $this->view->status['msg'] ?>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    <?php
    }
    ?>
    <!-- Formulario para cadastro do novo usuário -->
    <form action="/salvar_usuario" method="POST" enctype="multipart/form-data">

        <!-- Dados do usuário -->
        <div class="row">
            <div class="col-12 col-md-8 mb-3">
                <label for="nome" class="form-label">Nome</label>
                <input type="text" class="form-control" name="nome" value="<?= isset($this->view->temusuario['nome'])
                 ? $this->view->temusuario['nome'] : "" ;?>" id="nome" title="digite o nome do usuário" required>
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-md-8 mb-3">
                <label for="sobrenome" class="form-label">Sobrenome</label>
                <input type="text" class="form-control" name="sobrenome" value="<?= isset($this->view->temusuario['sobrenome'])
                 ? $this->view->temusuario['sobrenome'] : "" ;?>" id="sobrenome" title="digite o sobrenome do usuário" required>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-md-8 mb-3">
                <label for="file_imagem" class="form-label">Envie um arquivo de imagem (Opcional)</label>
                <input type="file" name="file_imagem" id="file_imagem" class="form-control" accept="image/*">
            </div>
        </div>

        <!-- dados de login -->
        <div class="row">
            <div class="col-12 col-md-8 mb-3">
                <label for="email" class="form-label">E-mail</label>
                <input type="text" class="form-control" name="email" value="<?= isset($this->view->temusuario['email'])
                 ? $this->view->temusuario['email'] : "" ;?>" id="email" title="digite o e-mail que será utilizado para login" required>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-md-5 mb-3">
                <label for="senha" class="form-label">Senha</label>
                <input type="password" class="form-control" name="senha" value="<?= isset($this->view->temusuario['senha'])
                 ? $this->view->temusuario['senha'] : "" ;?>" id="senha" title="digite a senha do usuário" required>
            </div>
        </div>



        <div class="row">
            <div class="col-12 col-md-3 mb-1 mt-1">
                <input type="checkbox" class="btn-check" id="btn-check-outlined" name="nivel"  

                <?php
                 if(isset($this->view->temusuario['nivel']) && $this->view->temusuario['nivel'] == 1){
                 echo "checked";
                 }
                 ?>
                
                autocomplete="off">
                <label class="btn btn-outline-primary" for="btn-check-outlined">Administrador</label><br>
            </div>
        </div>
        <?php
        
        ?>

        <hr>

        <div class="row mt-3">
            <div class="col-12 col-md-6 mb-3">
                <input class="btn btn-primary" type="submit" value="Salvar" />
            </div>
        </div>
    </form>
</div>